- name: Unzip project content
  run: |
    mkdir content
    unzip "kids.zip" -d content

- name: Create Cordova Project
  run: |
    cordova create myapp com.example.kidslearning "Kids Learning Fun"
    cd myapp
    cordova platform add android
    cd ..
    cp -r content/kids-learning-fun/* myapp/www/
